apiVersion: v2
name: jenkins-saas
description: "Jenkins configured as code for SaaS environments"
type: application
version: 1.0.0
appVersion: "2.479.1"

dependencies:
  - name: jenkins
    version: "5.7.20"
    repository: "https://charts.jenkins.io"